### PR TITLE
Change redundant conditions in OpportunitiesController

### PR DESCRIPTION
**Pull request by sunxiaoguang**
There are two redundant conditions in OpportunitiesController.php:246

### CODE REVIEW

**Comment by SMEWebify** [comment]
@sunxiaoguang nice catch, partialy true

These are the following variables that should be controlled

``` php
$accounting_payment_conditions = AccountingPaymentConditions::select('id')->where( 'default', 1)->first(); 
$accounting_payment_methods = AccountingPaymentMethod::select('id')->where( 'default', 1)->first(); 
$accounting_deliveries = AccountingDelivery::select('id')->where( 'default', 1)->first(); 

```

**Review by SMEWebify — CHANGES_REQUESTED** [review]
@sunxiaoguang nice catch, partialy true

These are the following variables that should be controlled

``` php
$accounting_payment_conditions = AccountingPaymentConditions::select('id')->where( 'default', 1)->first(); 
$accounting_payment_methods = AccountingPaymentMethod::select('id')->where( 'default', 1)->first(); 
$accounting_deliveries = AccountingDelivery::select('id')->where( 'default', 1)->first(); 

```

**Comment by sunxiaoguang** [comment]
> @sunxiaoguang nice catch, partialy true
> 
> These are the following variables that should be controlled
> 
> ```
> $accounting_payment_conditions = AccountingPaymentConditions::select('id')->where( 'default', 1)->first(); 
> $accounting_payment_methods = AccountingPaymentMethod::select('id')->where( 'default', 1)->first(); 
> $accounting_deliveries = AccountingDelivery::select('id')->where( 'default', 1)->first(); 
> ```

I see. Updated to control by these three variables. PTAL

**Review by SMEWebify — APPROVED** [review]

**Review by SMEWebify — APPROVED** [review]
Let's go

**Pull request merged**
